export const API = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
  },
  companies: '/companies',
  company: (id: string) => `/companies/${id}`,
  roles: '/roles',
  role: (id: string) => `/roles/${id}`,
  users: '/users',
  user: (id: string) => `/users/${id}`,
  branches: '/branches',
  branch: (id: string) => `/branches/${id}`,
  stores: '/stores',
  store: (id: string) => `/stores/${id}`,
  brands: '/brands',
  brand: (id: string) => `/brands/${id}`,
  categories: '/categories',
  categoryTree: '/categories/tree',
  category: (id: string) => `/categories/${id}`,
  products: '/products',
  product: (id: string) => `/products/${id}`,
} as const;
