export const API = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
  },
  companies: '/companies',
  company: (id: string) => `/companies/${id}`,
  roles: '/roles',
  role: (id: string) => `/roles/${id}`,
  users: '/users',
  user: (id: string) => `/users/${id}`,
  branches: '/branches',
  branch: (id: string) => `/branches/${id}`,
  stores: '/stores',
  store: (id: string) => `/stores/${id}`,
  brands: '/brands',
  brand: (id: string) => `/brands/${id}`,
  categories: '/categories',
  categoryTree: '/categories/tree',
  category: (id: string) => `/categories/${id}`,
  products: '/products',
  product: (id: string) => `/products/${id}`,
  productStocks: (productId: string) => `/inventory/products/${productId}`,
  productStock: (id: string) => `/inventory/${id}`,
  productFeatures: '/product-features',
  productFeaturesByProduct: (productId: string) => `/product-features/products/${productId}`,
  productFeature: (id: string) => `/product-features/${id}`,
  productPriceTiers: '/product-price-tiers',
  productPriceTiersByProduct: (productId: string) => `/product-price-tiers/products/${productId}`,
  productPriceTier: (id: string) => `/product-price-tiers/${id}`,
  productBundles: '/product-bundles',
  productBundle: (id: string) => `/product-bundles/${id}`,
  currencies: '/currencies',
  currency: (id: string) => `/currencies/${id}`,
  currencyDefault: (id: string) => `/currencies/${id}/default`,
  orders: '/orders',
  order: (id: string) => `/orders/${id}`,
  orderStatus: (id: string) => `/orders/${id}/status`,
  orderPaymentStatus: (id: string) => `/orders/${id}/payment-status`,
  uploadImage: '/uploads/image',
  customers: '/customers',
  customer: (id: string) => `/customers/${id}`,
  customerPoints: (id: string) => `/customers/${id}/points`,
  customerPointsAdjust: (id: string) => `/customers/${id}/points/adjust`,
  deals: '/deals',
  deal: (id: string) => `/deals/${id}`,
  dealStage: (id: string) => `/deals/${id}/stage`,
  whatsappMessages: (customerId: string) => `/whatsapp/customers/${customerId}/messages`,
  whatsappRules: '/whatsapp/rules',
  whatsappRule: (id: string) => `/whatsapp/rules/${id}`,
  raffles: '/raffles',
  raffle: (id: string) => `/raffles/${id}`,
  raffleStatus: (id: string) => `/raffles/${id}/status`,
  raffleEligible: (id: string) => `/raffles/${id}/eligible`,
  raffleDraw: (id: string) => `/raffles/${id}/draw`,
  rafflePrize: (id: string) => `/raffles/${id}/prize`,
  devToolsSeeds: '/dev-tools/seeds',
  devToolsSeedsRunAll: '/dev-tools/seeds/run',
  devToolsSeedRun: (id: string) => `/dev-tools/seeds/${id}/run`,
  devToolsSeedDelete: (id: string) => `/dev-tools/seeds/${id}`,
  devToolsWipeDatabase: '/dev-tools/seeds/database/all',
} as const;
